language: python
sudo: require
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python -m compileall ./
  - coverage run -m unittest discover -s . -v -p "*_test.py"

after_success:
  - coveralls

notifications:
  email: false
